# Generated by Django 4.2 on 2026-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('thumb', models.BooleanField()),
                ('index', models.BooleanField()),
                ('middle', models.BooleanField()),
                ('ring', models.BooleanField()),
                ('pinky', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('sign', 'Sign Language'), ('voice', 'Voice'), ('text', 'Text')], max_length=10)),
                ('input_value', models.TextField()),
                ('output_value', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
