# Generated by Django 4.2 on 2026-01-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
