# Generated by Django 4.2 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_translation_user_alter_translation_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sign',
            name='middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sign',
            name='pinky',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sign',
            name='ring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sign',
            name='thumb',
            field=models.BooleanField(default=False),
        ),
    ]
